### PR TITLE
Prefer expanded methods for empty methods

### PR DESCRIPTION
**Pull request by ztoolson**
With this cop enabled:

```
def show; end`
```

With the new style:

```
def show
end
```

//RFC @mattnichols @film42

### CODE REVIEW

**Comment by ztoolson** [comment]
Here is the cop: http://rubocop.readthedocs.io/en/latest/cops_style/#styleemptymethod

**Comment by mattnichols** [comment]
:shipit:

**Comment by mattnichols** [comment]
☝️ Beat me to it!

**Comment by liveh2o** [comment]
84cdacb4-f226-11e6-8ee1-511c30199a1c

**Pull request merged**
